---
- name: common pkg install
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git-core
    - build-essential
    - python-dev
    - python-pip
    - python3-dev
    - curl
    - libcurl4-openssl-dev
    - libncursesw5-dev
    - libgdbm-dev
    - libc6-dev
    - zlib1g-dev
    - libsqlite3-dev
    - tk-dev
    - libssl-dev
    - openssl
    - libbz2-dev
    - libreadline-dev

- name: OS upgrade
  apt: upgrade=dist update_cache=yes
