---
# vim setup

- name: vim pkg install
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - vim

- name: Neobundle install check
  sudo: no
  shell: ls -ld ~/.vim/bundle/neobundle.vim
  register: result
  failed_when: "'FAILED' in result.stderr"

- name: Neobundle install
  sudo: no
  git: repo=https://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim
  when: result|failed
