---
- name: japanese pkg install
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - fonts-ipafont
    - fonts-ipaexfont

- name: japanese input pkg install
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - ibus-anthy

- name: japanese man install
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - manpages-ja
    - manpages-ja-dev

- name: create timezone file(Asia/Tokyo)
  copy : content='Asia/Tokyo'
         dest=/etc/timezone
         owner=root
         group=root
         mode=0644
         backup=yes

- name: update timezone
  shell: dpkg-reconfigure --frontend noninteractive tzdata
